services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
  db:
    image: postgres:17.0
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
